### ISSUE TITLE
Milestone 3 - Data Schema: Missing Submission!

### ISSUE THREAD

**Issue by minhkhang1795** [sbu-codepath-cleanse/Cleanse#7]
It appears that you have defined your data schema but it is not shown in your README. Also, you should plan to set up your Parse server. Please have your project updated as soon as possible!

Best,
Khang

**Comment by lee-see** [comment]
Updated Data Schema. Please review!

**Comment by minhkhang1795** [comment]
:+1: Nice work on getting the data schema defined! Now, you'll have 3 sprints (one week each) to complete all the required stories for your app and 2 sprints (one week each) to work on optionals and add polish. Let us know if we can help in any way!
